---
# tasks file for http-tomcat
- name: install tomcat
  yum:
    name: tomcat
    state: latest

- name: enable tomcat at boot
  service:
    name: tomcat
    enabled: yes


- name: create tomcat default web directory
  file:
    path: "{{ tomcat_web_root }}"
    state: directory

- name: copy static index.html to tomcat webroot
  template:
    src: index.html.j2
    dest: "{{ tomcat_web_root }}/index.html"
    mode: 0644

- name: start tomcat
  service:
    name: tomcat
    state: started

- name: install apache
  yum:
    name: httpd
    state: latest
    
- name: start and enable apache at boot
  service:
    name: httpd
    state: started
    enabled: yes
