---
- name: Set a fact about the Ansible python interpreter
  set_fact:
    old_ansible_python_interpreter: "{{ ansible_python_interpreter | default('/usr/bin/python') }}"

- name: Set a fact to ensure Ansible uses the python interpreter in the virtualenv
  set_fact:
    ansible_python_interpreter: "{{ os_flavors_venv }}/bin/python"

# - name: Print records
#   debug:
#     msg: " Users have this much Memory {{ item.ram }} and Name {{ item.name }}"
#   tags:
#     - test3
#   with_items: 
#     - "{{ os_flavors }}"

- name: Ensure nova flavors exist
  os_nova_flavor:
    auth_type: "{{ os_flavors_auth_type }}"
    auth: "{{ os_flavors_auth }}"
    name: "{{ item.name }}"
    ram: "{{ item.ram }}"
    vcpus: "{{ item.vcpus }}"
    disk: "{{ item.disk }}"
    ephemeral: "{{ item.ephemeral | default(omit) }}"
    swap: "{{ item.swap | default(omit) }}"
    is_public: "{{ item.is_public | default(omit) }}"
    extra_specs: "{{ item.extra_specs | default(omit) }}"
    state: present
    cloud: "{{ item.cloud_name }}"
  with_items: 
    - "{{ os_flavors }}"




# This variable is unset before we set it, and it does not appear to be
# possible to unset a variable in Ansible.
- name: Set a fact to reset the Ansible python interpreter
  set_fact:
    ansible_python_interpreter: "{{ old_ansible_python_interpreter }}"
