---
# tasks file for osp.keypair
  - name: Generate key files
    user:
      name: "{{ ansible_env.USER }}"
      generate_ssh_key: yes
      ssh_key_file: .ssh/test_id_rsa
  - os_keypair:
      cloud: osp_cloud
      state: present
      name: ansible_ssh
      public_key_file: "{{ ansible_env.HOME }}/.ssh/test_id_rsa.pub"
    register: key
    ignore_errors: True
    tags:
      - keypair


# This block runs only if previous task failed, and forces the key update
  - block:
    - name: Remove old keypair
      os_keypair:
          cloud: "osp_cloud"
          name: ansible_ssh
          public_key_file: "{{ ansible_env.HOME }}/.ssh/test_id_rsa.pub"
          state: absent

    - name: Add updated keypair
      os_keypair:
          cloud: osp_cloud
          state: present
          name: ansible_ssh
          public_key_file: "{{ ansible_env.HOME }}/.ssh/test_id_rsa.pub"
      register: key
    when:
      - key.failed
      - '"present but key hash not the same as offered. Delete key first." in key.msg'